name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to use for the build'
        required: true
      repo:
        description: 'Target docker repository to push the image to'
        required: true
        type: choice
        default: 'dockerhub.milesight.cn/beaver-iot'
        options:
          - dockerhub.milesight.cn/beaver-iot
          - milesight
          - dockerhub.milesight.cn/milesight
      target_platform:
        description: 'The URL to use for the build'
        required: true
        type: choice
        default: 'linux/arm64,linux/amd64'
        options:
          - linux/arm64,linux/amd64
          - linux/amd64
          - linux/arm64
      web_git_repo_url:
        description: 'The URL of the web git repository'
        required: true
        default: 'https://github.com/milesight-iot/beaver-iot-web.git'
      web_git_branch:
        description: 'The branch of the web git repository'
        required: true
        default: 'origin/release'
      api_git_repo_url:
        description: 'The URL of the API git repository'
        required: true
        default: 'https://github.com/milesight-iot/beaver-iot.git'
      api_git_branch:
        description: 'The branch of the API git repository'
        required: true
        default: 'origin/main'
      api_mvn_profile:
        description: 'The Maven profile to use for the API build'
        required: true
        default: 'release'
        type: choice
        options:
            - release
            - snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Show Buildx version
        run: docker buildx version
      - name: Set registry credentials
        id: set-creds
        run: |
          if [ "${{ github.event.inputs.repo }}" = "milesight" ]; then
            echo "DOCKER_SCOPE=PUBLIC" >> $GITHUB_ENV
          else
            echo "DOCKER_SCOPE=PRIVATE" >> $GITHUB_ENV
          fi
      - name: Login To Private Docker Registry
        if: env.DOCKER_SCOPE == 'PRIVATE'
        uses: docker/login-action@v3
        with:
          registry: dockerhub.milesight.cn
          username: ${{ secrets.MILESIGHT_DOCKER_USERNAME }}
          password: ${{ secrets.MILESIGHT_DOCKER_PASSWORD }}
      - name: Login To Public Docker Registry
        if: env.DOCKER_SCOPE == 'PUBLIC'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Run Build Script
        working-directory: build-docker
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          DOCKER_BUILD_OPTION_PUSH: true
          DOCKER_BUILD_OPTION_LOAD: false
          DOCKER_BUILD_OPTION_NO_CACHE: true
          DOCKER_REPO: ${{ github.event.inputs.repo }}
          TARGET_PLATFORM: ${{ github.event.inputs.target_platform }}
          PRODUCTION_TAG: ${{ github.event.inputs.tag }}
          WEB_GIT_REPO_URL: ${{ github.event.inputs.web_git_repo_url }}
          WEB_GIT_BRANCH: ${{ github.event.inputs.web_git_branch }}
          API_GIT_REPO_URL: ${{ github.event.inputs.api_git_repo_url }}
          API_GIT_BRANCH: ${{ github.event.inputs.api_git_branch }}
          API_MVN_PROFILE: ${{ github.event.inputs.api_mvn_profile }}